spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pisito_db
    username: pisito_user
    password: pisito_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

ollama:
  base-url: http://localhost:11434
  model: llama3.1:8b
spotify:
  api-base-url: https://api.spotify.com/v1
  auth-base-url: https://accounts.spotify.com
  client-id: ${SPOTIFY_CLIENT_ID:}
  client-secret: ${SPOTIFY_CLIENT_SECRET:}
app:
  upload:
    dir: uploads
